config/routes.rb
Project2::Application.routes.draw do
  root to: 'static_pages#home'

  match '/hobbies',    to: 'static_pages#hobbies'
  match '/projects',   to: 'static_pages#projects'
  match '/contact', to: 'static_pages#contact'
  match '/resume', to: 'static_pages#resume'
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def resume
  end

  def projects
  end

  def hobbies
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "Bryce Hower"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Special thanks to
    <a href="http://railstutorial.org/">Rails Tutorial</a>
    by Michael Hartl and to <a href="http://engineering.utsa.edu/~krishnan/">Dr. Ram Krishnan</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "Resume",   resume_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "Bryce Hower", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home",    root_path %></li>
          <li><%= link_to "Resume",    resume_path %></li>
          <li><%= link_to "Projects",    projects_path %></li>
          <li><%= link_to "Hobbies",    hobbies_path %></li>
          <li><%= link_to "How to contact",  contact_path %></li>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>    
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
  Office Number: 831-671-5750
  <br>
  Email Address: bau099@utsa.edu
</p>

app/views/static_pages/hobbies.html.erb
<% provide(:title, 'Hobbies') %>
<h1>Hobbies</h1>
<p>
In my free time I enjoy playing guitar and have played in university ensemble. I also enjoy mountain biking and hiking in general.
</p>

app/views/static_pages/home.html.erb
<div class="center hero-unit">
  <h1><%= link_to image_tag("me.jpg",:width => "50%", alt: "Rails", ), 'http://rubyonrails.org/' %> Bryce Hower</h1>

  <h2>
    General Dynamics C4 Systems
  </h2>
  <h3>
    SCCT(Secure Communications and Computer Technologies)
  </h3>

</div>

app/views/static_pages/projects.html.erb
<% provide(:title, 'Projects') %>
<h1>Projects</h1>
<p>
 As a recent grad, I have worked on projects in various engineering topics. I have listed some of the more noteworthy projects here:
 <br>
 <br>
 <a href="http://aux.coe.utsa.edu/~Team03/">My senior design project</a> was a local indoor positioning system for precise small-scale positioning. We incorporated a Wii infrared camera and ultrasonic rangefinder into a pan/tilt system to accurately track a infrared target.
 <br>
 <br>
 In VLSI and computer architecture, I designed the layouts and photomasks for multiple MOSFET designs. In verilog I also designed a working Pipelined MIPS Processor.
</p>

app/views/static_pages/resume.html.erb
<% provide(:title, 'Resume') %>
<h1>Resume</h1>
<p>
My resume can be found here in text form:
<br>
<a href="Bryce_resume.txt">My Resume (plain text)</a>
<br>
<br>
My resume can be found here in .pdf form:
<br>
<a href="Bryce_Resume.pdf">Resume (PDF)</a>
</p>